objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <externalId>true</externalId>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EmailManager.cls
public class EmailManager {

    public static void sendConfirmEmails(List<Candidate__c> lstCandidates, String replyAdress) {
    	List<Messaging.SingleEmailMessage> lstMail = new List<Messaging.SingleEmailMessage>();
    	EmailTemplate templateId = [SELECT Id FROM EmailTemplate WHERE Name = 'Interview Confirm' LIMIT 1];
  
    	for (Candidate__c candidate: lstCandidates) {
    		Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
			mail.setReplyTo(replyAdress);
			String[] toAddresses = new String[] {candidate.Email__c};
	        mail.setToAddresses(toAddresses);
	       /* mail.setTemplateID(templateId.Id); 
			mail.setTargetObjectId(candidate.LastModifiedById);
			mail.setWhatId(candidate.Id);*/
			mail.setSubject('Candidate Confirmation');
	        mail.setPlainTextBody('Dear '+ candidate.First_Name__c +'\nThank you for joining our interview. We would like to invite you to join our company, please check our offer details in attachment file and send your confirmation about this.\n\nThank you for reading this mail.');
	     
			mail.setSaveAsActivity(false);
	       	lstMail.add(mail);
    	}
		Messaging.sendEmail(lstMail);
    }
}